package com.example.meditrack.report

import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Rect
import android.graphics.RectF
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import android.text.StaticLayout
import android.text.TextPaint
import com.example.meditrack.clinical.VitalStatus

/**
 * A tiny layout engine on top of [PdfDocument]: it tracks a Y cursor down an A4 page,
 * starts a new page automatically when content would overflow, and offers medical-
 * report primitives (section bands, key/value rows, tables, charts, footers).
 *
 * Page count for "Page X of Y" is not known until the whole document is laid out, so
 * the generator renders twice: once with [totalPages] = null to count pages, then
 * again with the real total. The drawing is cheap (bitmaps are pre-rendered), so the
 * second pass is fast.
 */
class PdfCanvasWriter(
    private val totalPages: Int?,
    private val patientName: String,
    private val generatedLabel: String,
) {
    val document = PdfDocument()

    private val pageW = 595
    private val pageH = 842
    private val left = 40f
    private val right = pageW - 40f
    private val top = 48f
    private val bottomLimit = pageH - 60f
    val contentWidth = right - left

    private var page: PdfDocument.Page? = null
    private var canvas: Canvas = Canvas()
    private var y = top
    private var pageNo = 0

    // ── Palette ──────────────────────────────────────────────────────────────
    private val teal = Color.rgb(40, 102, 110)
    private val charcoal = Color.rgb(11, 41, 53)
    private val storm = Color.rgb(228, 230, 231)
    private val darkText = Color.rgb(40, 44, 48)
    private val grey = Color.rgb(120, 124, 128)

    private val bold = Typeface.create(Typeface.DEFAULT, Typeface.BOLD)

    private val bandPaint = Paint().apply { color = teal; style = Paint.Style.FILL }
    private val brandPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = Color.WHITE; textSize = 22f; typeface = bold }
    private val brandSubPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = Color.WHITE; textSize = 12f }
    private val sectionTextPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = Color.WHITE; textSize = 13f; typeface = bold }
    private val headingPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = charcoal; textSize = 13f; typeface = bold }
    private val labelPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = charcoal; textSize = 11f; typeface = bold }
    private val bodyPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = darkText; textSize = 11f }
    private val tablePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = darkText; textSize = 10f }
    private val tableBoldPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = charcoal; textSize = 10f; typeface = bold }
    private val notePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = grey; textSize = 9.5f }
    private val footerPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = grey; textSize = 8f }
    private val disclaimerPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply { color = grey; textSize = 7.5f }
    private val tableHeaderBg = Paint().apply { color = storm; style = Paint.Style.FILL }
    private val rulePaint = Paint().apply { color = storm; strokeWidth = 1f }
    private val bitmapPaint = Paint().apply { isFilterBitmap = true; isAntiAlias = true }
    private val bodyTextPaint = TextPaint(bodyPaint)

    // ── Page lifecycle ───────────────────────────────────────────────────────
    fun begin() = newPage()

    fun finish(): Int {
        closePage()
        return pageNo
    }

    private fun newPage() {
        closePage()
        pageNo++
        val info = PdfDocument.PageInfo.Builder(pageW, pageH, pageNo).create()
        page = document.startPage(info)
        canvas = page!!.canvas
        y = top
    }

    private fun closePage() {
        val p = page ?: return
        drawFooter(p.canvas)
        document.finishPage(p)
        page = null
    }

    private fun ensureSpace(h: Float) {
        if (y + h > bottomLimit) newPage()
    }

    private fun drawFooter(c: Canvas) {
        val fy = pageH - 38f
        c.drawLine(left, fy - 12, right, fy - 12, rulePaint)
        c.drawText("$patientName  ·  $generatedLabel", left, fy, footerPaint)
        val total = totalPages?.let { " of $it" } ?: ""
        val pageText = "Page $pageNo$total"
        c.drawText(pageText, right - footerPaint.measureText(pageText), fy, footerPaint)
        c.drawText(
            "Generated by MediTrack — reference ranges are adult defaults; not a substitute for professional medical judgement.",
            left, fy + 12, disclaimerPaint,
        )
    }

    // ── Primitives ───────────────────────────────────────────────────────────

    fun titleBlock(brand: String, subtitle: String, lines: List<String>) {
        canvas.drawRect(0f, 0f, pageW.toFloat(), 64f, bandPaint)
        canvas.drawText(brand, left, 30f, brandPaint)
        canvas.drawText(subtitle, left, 52f, brandSubPaint)
        y = 64f + 20f
        for (l in lines) {
            canvas.drawText(l, left, y, bodyPaint)
            y += 16f
        }
        y += 8f
    }

    fun sectionTitle(text: String) {
        ensureSpace(34f)
        canvas.drawRect(left, y, right, y + 22f, bandPaint)
        canvas.drawText(text, left + 8f, y + 15.5f, sectionTextPaint)
        y += 22f + 10f
    }

    fun subHeading(text: String) {
        ensureSpace(22f)
        canvas.drawText(text, left, y + 12f, headingPaint)
        y += 20f
    }

    fun keyValue(key: String, value: String) {
        ensureSpace(18f)
        val keyW = 150f
        canvas.drawText(key, left, y + 12f, labelPaint)
        canvas.drawText(fit(value.ifBlank { "—" }, bodyPaint, contentWidth - keyW), left + keyW, y + 12f, bodyPaint)
        y += 19f
    }

    fun paragraph(text: String) {
        if (text.isBlank()) return
        drawWrapped(text, left, contentWidth)
        y += 4f
    }

    fun bullet(text: String) {
        drawWrapped("•  $text", left + 6f, contentWidth - 6f)
        y += 2f
    }

    fun note(text: String) {
        ensureSpace(14f)
        canvas.drawText(fit(text, notePaint, contentWidth), left, y + 10f, notePaint)
        y += 15f
    }

    fun spacer(h: Float) { y += h }

    /** Draw a table row across the content width; [colors] overrides text color per column. */
    fun tableRow(
        cells: List<String>,
        widths: List<Float>,
        header: Boolean = false,
        colors: Map<Int, Int> = emptyMap(),
    ) {
        val rowH = 18f
        ensureSpace(rowH)
        if (header) canvas.drawRect(left, y, right, y + rowH, tableHeaderBg)
        var x = left
        val base = if (header) tableBoldPaint else tablePaint
        cells.forEachIndexed { i, cell ->
            val w = widths.getOrElse(i) { 60f }
            val paint = colors[i]?.let { Paint(base).apply { color = it } } ?: base
            canvas.drawText(fit(cell, paint, w - 6f), x + 3f, y + rowH - 5f, paint)
            x += w
        }
        y += rowH
    }

    fun image(bitmap: Bitmap, maxHeight: Float? = null) {
        var w = contentWidth
        var h = bitmap.height * (contentWidth / bitmap.width)
        if (maxHeight != null && h > maxHeight) {
            w *= maxHeight / h
            h = maxHeight
        }
        ensureSpace(h + 8f)
        canvas.drawBitmap(bitmap, Rect(0, 0, bitmap.width, bitmap.height), RectF(left, y, left + w, y + h), bitmapPaint)
        y += h + 8f
    }

    // ── Helpers ──────────────────────────────────────────────────────────────

    private fun drawWrapped(text: String, x: Float, width: Float) {
        val layout = StaticLayout.Builder
            .obtain(text, 0, text.length, bodyTextPaint, width.toInt().coerceAtLeast(1))
            .build()
        ensureSpace(layout.height.toFloat().coerceAtMost(bottomLimit - top))
        canvas.save()
        canvas.translate(x, y)
        layout.draw(canvas)
        canvas.restore()
        y += layout.height
    }

    private fun fit(text: String, paint: Paint, maxW: Float): String {
        if (paint.measureText(text) <= maxW) return text
        var t = text
        while (t.isNotEmpty() && paint.measureText("$t…") > maxW) t = t.dropLast(1)
        return "$t…"
    }

    companion object {
        fun statusColorInt(status: VitalStatus): Int = when (status) {
            VitalStatus.NORMAL -> Color.rgb(67, 160, 71)
            VitalStatus.WARNING -> Color.rgb(251, 140, 0)
            VitalStatus.CRITICAL -> Color.rgb(211, 47, 47)
        }
    }
}
